<a href="https://colab.research.google.com/github/akhilkumarb/FML/blob/main/50_Startups2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#cycle 1
#company data set
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error

In [ ]:
df=pd.read_csv("/content/50_Startups.csv")
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
X=df.drop(labels=['State','Profit'] , axis=1).values

y=df['Profit'].values
print(X ,y)


[[165349.2  136897.8  471784.1 ]
 [162597.7  151377.59 443898.53]
 [153441.51 101145.55 407934.54]
 [144372.41 118671.85 383199.62]
 [142107.34  91391.77 366168.42]
 [131876.9   99814.71 362861.36]
 [134615.46 147198.87 127716.82]
 [130298.13 145530.06 323876.68]
 [120542.52 148718.95 311613.29]
 [123334.88 108679.17 304981.62]
 [101913.08 110594.11 229160.95]
 [100671.96  91790.61 249744.55]
 [ 93863.75 127320.38 249839.44]
 [ 91992.39 135495.07 252664.93]
 [119943.24 156547.42 256512.92]
 [114523.61 122616.84 261776.23]
 [ 78013.11 121597.55 264346.06]
 [ 94657.16 145077.58 282574.31]
 [ 91749.16 114175.79 294919.57]
 [ 86419.7  153514.11      0.  ]
 [ 76253.86 113867.3  298664.47]
 [ 78389.47 153773.43 299737.29]
 [ 73994.56 122782.75 303319.26]
 [ 67532.53 105751.03 304768.73]
 [ 77044.01  99281.34 140574.81]
 [ 64664.71 139553.16 137962.62]
 [ 75328.87 144135.98 134050.07]
 [ 72107.6  127864.55 353183.81]
 [ 66051.52 182645.56 118148.2 ]
 [ 65605.48 153032.06 107138.38]
 [ 61994.4

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)


(37, 3) (13, 3) (37,) (13,)


In [ ]:
reg = linear_model.Lasso(alpha=0.30)
reg.fit(X_train,y_train)

Lasso(alpha=0.3)

In [ ]:
y_predict=reg.predict(X_test)

In [ ]:
print(mean_absolute_error(y_test, y_predict))
print(mean_squared_error(y_test, y_predict))
print(np.sqrt(mean_squared_error(y_test, y_predict)))
print(r2_score(y_test, y_predict))
     

8505.173135542758
160826552.5997532
12681.740913603038
0.9364356316670673


In [ ]:
plt.figure