<a href="https://colab.research.google.com/github/akhilkumarb/FML/blob/main/sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import sklearn.metrics as sk
import numpy as np
from sklearn.model_selection import train_test_split
X = np.array([1,2,3,4,5,6,7,8,9])
y = np.array([2,4,6,8,10,12,14,16,18])
X_train , X_test , y_train , y_test = train_test_split(X,y,random_state=0)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[5 9 7 4 1 6]
[10 18 14  8  2 12]
[8 3 2]
[16  6  4]


In [21]:
X_train , X_test , y_train , y_test = train_test_split(X,y,random_state=100)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[5 3 8 4 1 9]
[10  6 16  8  2 18]
[2 7 6]
[ 4 14 12]


In [19]:
#mean absolute error(MAE)
y_predict = np.array([2,4,7,8,11,14,12,15,18])
sk.mean_absolute_error(y,y_predict)

0.7777777777777778

In [37]:
#mean square error(MSE)
sk.mean_squared_error(y,y_predict)

1.2222222222222223

In [34]:
#root mean square error(RMSE)
np.sqrt(sk.mean_squared_error(y,y_predict))

1.1055415967851334

In [35]:
#r2 score
sk.r2_score(y,y_predict)

0.9541666666666667

In [42]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/dataset/Iris.csv')
print(df)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

In [46]:
y=df['Species']
y
X=df.drop(labels='Species' ,axis=1,inplace=False)
X

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]